apiVersion: v1
kind: Service
metadata:
  name: package-json-image
  labels:
    app: package-json-image
spec:
  ports:
  - port: 3000
    protocol: TCP
  clusterIP: None
  selector:
    app: package-json-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-json-image
  labels:
    app: package-json-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-json-image
  template:
    metadata:
      labels:
        app: package-json-image
    spec:
      containers:
      - name: package-json-image
        image: package-json-image
